insert into hotel (id_hotel, hotel_name, stars_number, address) values (1, 'Алтай', 1, '451 Grasskamp Lane');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (2, 'Алтай', 5, '1352 Lunder Trail');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (3, 'Алтай', 4, '11122 Maple Wood Junction');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (4, 'Алтай', 4, '69779 Heffernan Center');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (5, 'Алтай', 4, '4 Corscot Pass');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (6, 'Алтай', 2, '96979 Crest Line Court');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (7, 'Восток', 3, '677 Duke Crossing');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (8, 'Восток', 5, '7383 Miller Point');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (9, 'Восток', 2, '1 Northridge Plaza');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (10, 'Восток', 1, '8908 Homewood Pass');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (11, 'Восток', 4, '11362 Coolidge Avenue');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (12, 'Восток', 5, '1 Manufacturers Park');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (13, 'Восток', 2, '7 Glendale Alley');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (14, 'Восток', 5, '36503 Tennyson Crossing');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (15, 'Восток', 1, '2444 Fisk Trail');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (16, 'Восток', 3, '1 Saint Paul Way');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (17, 'Восток', 3, '62929 Red Cloud Drive');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (18, 'Космос', 2, '1959 New Castle Center');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (19, 'Космос', 1, '09094 Logan Place');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (20, 'Космос', 2, '8198 Village Parkway');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (21, 'Космос', 1, '95 Ridgeview Terrace');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (22, 'Космос', 4, '0497 Heath Road');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (23, 'Космос', 5, '09358 Fallview Road');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (24, 'Космос', 5, '09897 Bultman Junction');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (25, 'Космос', 2, '259 Badeau Street');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (26, 'Космос', 5, '4458 Maywood Drive');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (27, 'Космос', 1, '2009 Rusk Lane');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (28, 'Космос', 1, '278 Summit Alley');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (29, 'Космос', 3, '6 Sachs Avenue');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (30, 'Сокол', 2, '7 Mifflin Park');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (31, 'Сокол', 5, '2333 Tennessee Pass');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (32, 'Сокол', 1, '897 4th Terrace');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (33, 'Сокол', 2, '07 Loomis Point');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (34, 'Сокол', 5, '166 Norway Maple Center');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (35, 'Сокол', 4, '90803 Lakewood Gardens Lane');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (36, 'Сокол', 2, '2888 Anderson Hill');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (37, 'Сокол', 5, '55 Kensington Road');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (38, 'Сокол', 3, '6 Thierer Drive');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (39, 'Сокол', 2, '3 Sunfield Way');
insert into hotel (id_hotel, hotel_name, stars_number, address) values (40, 'Сокол', 4, '2899 Bultman Circle');
