insert into goods_catalog (id_catalog, name) values (1, 'Community Outreach Specialist');
insert into goods_catalog (id_catalog, name) values (2, 'Assistant Manager');
insert into goods_catalog (id_catalog, name) values (3, 'Desktop Support Technician');
insert into goods_catalog (id_catalog, name) values (4, 'Computer Systems Analyst IV');
insert into goods_catalog (id_catalog, name) values (5, 'Actuary');
insert into goods_catalog (id_catalog, name) values (6, 'Financial Analyst');
insert into goods_catalog (id_catalog, name) values (7, 'Environmental Specialist');
insert into goods_catalog (id_catalog, name) values (8, 'Budget/Accounting Analyst III');
insert into goods_catalog (id_catalog, name) values (9, 'Dental Hygienist');
insert into goods_catalog (id_catalog, name) values (10, 'Human Resources Manager');
insert into goods_catalog (id_catalog, name) values (11, 'Web Developer IV');
insert into goods_catalog (id_catalog, name) values (12, 'Community Outreach Specialist');
insert into goods_catalog (id_catalog, name) values (13, 'Registered Nurse');
insert into goods_catalog (id_catalog, name) values (14, 'Biostatistician III');
insert into goods_catalog (id_catalog, name) values (15, 'Product Engineer');
insert into goods_catalog (id_catalog, name) values (16, 'Physical Therapy Assistant');
insert into goods_catalog (id_catalog, name) values (17, 'Nurse Practicioner');
insert into goods_catalog (id_catalog, name) values (18, 'Quality Control Specialist');
insert into goods_catalog (id_catalog, name) values (19, 'Dental Hygienist');
insert into goods_catalog (id_catalog, name) values (20, 'Pharmacist');
insert into goods_catalog (id_catalog, name) values (21, 'Tax Accountant');
insert into goods_catalog (id_catalog, name) values (22, 'Sales Representative');
insert into goods_catalog (id_catalog, name) values (23, 'Human Resources Assistant I');
insert into goods_catalog (id_catalog, name) values (24, 'Marketing Assistant');
insert into goods_catalog (id_catalog, name) values (25, 'Automation Specialist III');
insert into goods_catalog (id_catalog, name) values (26, 'Desktop Support Technician');
insert into goods_catalog (id_catalog, name) values (27, 'Compensation Analyst');
insert into goods_catalog (id_catalog, name) values (28, 'Nurse Practicioner');
insert into goods_catalog (id_catalog, name) values (29, 'Financial Analyst');
insert into goods_catalog (id_catalog, name) values (30, 'Junior Executive');
insert into goods_catalog (id_catalog, name) values (31, 'Staff Scientist');
insert into goods_catalog (id_catalog, name) values (32, 'Marketing Manager');
insert into goods_catalog (id_catalog, name) values (33, 'Legal Assistant');
insert into goods_catalog (id_catalog, name) values (34, 'Actuary');
insert into goods_catalog (id_catalog, name) values (35, 'Analyst Programmer');
insert into goods_catalog (id_catalog, name) values (36, 'Software Engineer I');
insert into goods_catalog (id_catalog, name) values (37, 'Payment Adjustment Coordinator');
insert into goods_catalog (id_catalog, name) values (38, 'Junior Executive');
insert into goods_catalog (id_catalog, name) values (39, 'Accounting Assistant I');
insert into goods_catalog (id_catalog, name) values (40, 'Developer II');
insert into goods_catalog (id_catalog, name) values (41, 'Help Desk Operator');
insert into goods_catalog (id_catalog, name) values (42, 'Staff Scientist');
insert into goods_catalog (id_catalog, name) values (43, 'Clinical Specialist');
insert into goods_catalog (id_catalog, name) values (44, 'Associate Professor');
insert into goods_catalog (id_catalog, name) values (45, 'Software Engineer II');
insert into goods_catalog (id_catalog, name) values (46, 'Budget/Accounting Analyst I');
insert into goods_catalog (id_catalog, name) values (47, 'Junior Executive');
insert into goods_catalog (id_catalog, name) values (48, 'Human Resources Manager');
insert into goods_catalog (id_catalog, name) values (49, 'Sales Associate');
insert into goods_catalog (id_catalog, name) values (50, 'Help Desk Technician');
